# Generated by Django 2.2.23 on 2021-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
