# Generated by Django 2.2.23 on 2021-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0007_auto_20210622_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
