# Generated by Django 2.2.23 on 2021-06-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0008_auto_20210624_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modify_date',
        ),
    ]
