# Generated by Django 2.2.23 on 2021-06-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
